#!/bin/bash

# 毒舌老友 - 简单部署脚本
# 使用方法: ./deploy-simple.sh

echo "========================================"
echo "毒舌老友 - 阿里云服务器简单部署"
echo "========================================"
echo "服务器: YOUR_SERVER_IP"
echo "用户名: root"
echo "端口: 22"
echo "========================================"
echo ""

echo "这个脚本将指导你完成部署步骤。"
echo "你需要手动执行一些命令。"
echo ""

# 步骤1: 测试SSH连接
echo "[1/6] 测试SSH连接"
echo "请执行以下命令测试连接:"
echo "  ssh root@YOUR_SERVER_IP"
echo ""
read -p "按回车继续..." 

# 步骤2: 检查服务器环境
echo ""
echo "[2/6] 检查服务器环境"
echo "登录服务器后，检查是否已安装Docker和Docker Compose:"
echo ""
echo "检查Docker:"
echo "  docker --version"
echo ""
echo "检查Docker Compose:"
echo "  docker-compose --version"
echo ""
echo "如果没有安装，可以运行:"
echo "  apt-get update && apt-get install -y docker.io docker-compose"
echo ""
read -p "按回车继续..."

# 步骤3: 准备本地文件
echo ""
echo "[3/6] 准备本地文件"
echo "在本地电脑上，进入项目目录并创建部署包:"
echo "  cd ~/projects/toxic-friends"
echo "  tar -czf deploy.tar.gz --exclude=venv --exclude=__pycache__ --exclude=*.log ."
echo ""
echo "文件大小: $(cd ~/projects/toxic-friends && tar -czf /tmp/test.tar.gz --exclude=venv --exclude=__pycache__ --exclude=*.log . 2>/dev/null && ls -lh /tmp/test.tar.gz | awk '{print $5}' && rm /tmp/test.tar.gz)"
echo ""
read -p "按回车继续..."

# 步骤4: 上传文件
echo ""
echo "[4/6] 上传文件到服务器"
echo "在本地电脑上执行:"
echo "  scp deploy.tar.gz root@YOUR_SERVER_IP:/tmp/"
echo ""
echo "这会将文件上传到服务器的/tmp目录。"
echo "需要输入SSH密码。"
echo ""
read -p "按回车继续..."

# 步骤5: 在服务器上部署
echo ""
echo "[5/6] 在服务器上部署"
echo "登录服务器并执行以下命令:"
echo ""
echo "  # 创建项目目录"
echo "  mkdir -p /opt/toxic-friends"
echo "  cd /opt/toxic-friends"
echo ""
echo "  # 解压文件"
echo "  tar -xzf /tmp/deploy.tar.gz"
echo ""
echo "  # 设置权限"
echo "  chmod +x deploy.sh manage.sh"
echo ""
echo "  # 构建并启动"
echo "  docker-compose build"
echo "  docker-compose up -d"
echo ""
echo "  # 查看状态"
echo "  docker-compose ps"
echo ""
read -p "按回车继续..."

# 步骤6: 验证部署
echo ""
echo "[6/6] 验证部署"
echo "部署完成后，可以测试:"
echo ""
echo "1. 在服务器上测试:"
echo "   curl http://localhost:5004/health"
echo ""
echo "2. 在本地电脑上测试:"
echo "   curl http://YOUR_SERVER_IP:5004/health"
echo ""
echo "3. 在浏览器中访问:"
echo "   http://YOUR_SERVER_IP:5004"
echo ""
echo "========================================"
echo "🎉 部署指南完成！"
echo "========================================"
echo ""
echo "📱 访问地址:"
echo "   http://YOUR_SERVER_IP:5004"
echo ""
echo "🔧 常用命令:"
echo "   查看状态: docker-compose ps"
echo "   查看日志: docker-compose logs -f"
echo "   重启服务: docker-compose restart"
echo "   停止服务: docker-compose down"
echo ""
echo "📁 项目目录: /opt/toxic-friends"
echo "========================================"